[project] 
name = "RAG"
description = "RAG"
version = "v1"
company = "Oguzhan"
author = "Mert OGUZHAN" 

[logger]
filepath="./logs/rag.log"
rotation="50MB"

[semantic_chunker]
dataset_path = "/home/mert/projects/RAG/dataset/only_answer_medquad.txt"
embedding_model_name= "sentence-transformers/all-MiniLM-L6-v2"
threshold= 0.84
vector_db_path= "/home/mert/projects/RAG/app/vector_db"

[semantic_retriever]
embedding_model_name= "sentence-transformers/all-MiniLM-L6-v2"
vector_db_path= "/home/mert/projects/RAG/app/vector_db"
top_k = 3

[llm]
model_name= "llama3-8b-8192"
max_tokens = 512